name: Step 7, JS Actions

on:
  workflow_dispatch:
  issues:
    types: [labeled]

permissions:
  content: write

env:
  EXPECTED_METADATA: "second joke"

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/script/STEP)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
  action:
    name: Action Deployment
      steps:
      - name: ha-ha
        uses: ./.github/actions/joke-action
      - name: dog-list
        uses: ./.github/actions/dog-action
