name: JS Actions

on:
  issues:
    types: [labeled]

permissions:
  content: write

env:
  EXPECTED_METADATA: "second joke"
  
jobs:
  action:
    get_current_step:
      name: Check current step number
      runs-on: ubuntu-latest
    on_my_workflow_run:
      name: Check if my_workflow has run
      needs: get_current_step
      if: ${{ !github.event.repository.is_template }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: ha-ha
          if: contains(github.event, ${{ env.EXPECTED_METADATA }})
          uses: ./.github/actions/joke-action
        - name: dog-list
          uses: ./.github/actions/dog-action
