name: JS Actions

on:
  workflow_dispatch:
  issues:
    types: [labeled]

permissions:
  content: write
  
jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
  on_my_workflow_run:
    name: Check if my_workflow has run
    needs: get_current_step
  action:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ha-ha
        uses: ./.github/actions/joke-action
      - name: dog-list
        uses: ./.github/actions/dog-action
